export const GET_COMPANY_DATA_SUCCESS = "GET_COMPANY_DATA_SUCCESS";
export const GET_COMPANY_DATA_FAILURE = "GET_COMPANY_DATA_FAILURE";
export const GET_ADS_DATA_SUCCESS = "GET_ADS_DATA_SUCCESS";
export const GET_ADS_DATA_FAILURE = "GET_ADS_DATA_FAILURE";